/**
 * Browser-context transport for Qwen Web requests.
 *
 * All requests execute as `fetch` inside the authenticated Chromium page, so
 * cookies, TLS fingerprint and WAF posture are the real browser's. The Node
 * side never reconstructs the cookie jar.
 *
 * - `requestJson` runs a one-shot fetch and returns the complete body.
 * - `requestStream` relays an upstream `ReadableStream` incrementally through
 *   an `exposeBinding` bridge multiplexed by request id, so several streams
 *   can share one page without serializing whole generations.
 */
import {
  QWEN_WEB_BX_V,
  QWEN_WEB_CLIENT_CONTEXT_ARG,
  QWEN_WEB_CLIENT_VERSION,
  QWEN_WEB_DEFAULTS,
  QWEN_WEB_ENV,
  QWEN_WEB_STREAM_ABORTERS_KEY,
  QWEN_WEB_STREAM_BINDING,
} from "./constants"
import { QwenWebError, abortedError, classifyTransportFailure, isAbortLike } from "./errors"
import { debug } from "./log"
import { pageRequestHeaders, qwenWebOrigin, qwenWebUrl } from "./protocol"
import { QwenWebBrowser, type QwenWebPage, sharedBrowser } from "./browser"

/**
 * WAF signal headers the real web client attaches to requests that talk to
 * the completion backend. The page-side spy captures the live values (they
 * are per-session values generated by the UMID SDK), then `rawRequest*`
 * replays them from Node together with the browser's real cookies.
 *
 * `user-agent`, `accept-language` and the `sec-ch-ua*` client hints are
 * expected on completion traffic: without them the broker rejects the request
 * with `Bad_Request: Internal error` even though the WAF itself passes, so
 * they are captured from the browser's own requests and replayed with the
 * signals.
 */
export interface WafSignals {
  "bx-ua"?: string
  "bx-umidtoken"?: string
  "bx-v"?: string
  version?: string
  "user-agent"?: string
  "accept-language"?: string
  "sec-ch-ua"?: string
  "sec-ch-ua-mobile"?: string
  "sec-ch-ua-platform"?: string
}

const WAF_SIGNAL_KEYS = ["bx-ua", "bx-umidtoken", "bx-v", "version"] as const
/** Signal keys captured from the page but only replayed if present. */
const WAF_CAPTURE_KEYS = ["bx-ua", "bx-umidtoken"] as const
const CLIENT_HINT_KEYS = ["user-agent", "accept-language", "sec-ch-ua", "sec-ch-ua-mobile", "sec-ch-ua-platform"] as const
const WAF_SPY_STORAGE_KEY = "__alphacodeQwenWafSignals"
const WAF_SIGNAL_HARD_WAIT_MS = 15_000
/** Captured WAF tokens are valid for the page session; past this they may be a rotated set. */
const WAF_PAIR_TTL_MS = 5 * 60_000
/** After a full harvest miss, skip polling again for a while: WAF token issuance is per-load and flaky. */
const WAF_HARVEST_COOLDOWN_MS = 60_000

export interface QwenWebTransportOptions {
  browser?: QwenWebBrowser
  metadataTimeoutMs?: number
  idleTimeoutMs?: number
  reasoningIdleTimeoutMs?: number
  maxStreams?: number
  /** Chunk batching inside the page (first chunk always flushes immediately). */
  flushBytes?: number
  flushMs?: number
  /** Poll budget for streaming requests waiting on a captured WAF pair before degrading to static headers. */
  wafHardWaitMs?: number
  /** After a full WAF-harvest miss, skip polling again for this long (token issuance is per-load and flaky). */
  wafHarvestCooldownMs?: number
}

export interface RequestOptions {
  headers?: Record<string, string>
  body?: string
  referrer?: string
  timeoutMs?: number
  signal?: AbortSignal
  /**
   * False to reuse the page without steering it to the Qwen origin. Used by
   * background bookkeeping (model catalog refresh) that must never navigate
   * the shared page while a generation is streaming.
   */
  allowNavigate?: boolean
}

export interface JsonResponse {
  status: number
  statusText: string
  contentType: string
  body: string
}

export interface StreamResponse {
  status: number
  contentType: string
  stream: ReadableStream<Uint8Array>
  /** Abort the upstream fetch and release the slot. */
  abort: () => void
}

type BridgeEvent =
  | { type: "headers"; status: number; contentType: string }
  | { type: "chunk"; data: string }
  | { type: "done" }
  | { type: "error"; message: string; errorName?: string }

interface StreamState {
  chunks: Uint8Array[]
  done: boolean
  error: Error | undefined
  metadata: { status: number; contentType: string } | undefined
  waiters: Set<() => void>
}

interface BridgeScriptArgs {
  url: string
  method: string
  headers: Record<string, string>
  body?: string
  referrer?: string
  requestId: string
  bindingName: string
  abortersKey: string
  flushBytes: number
  flushMs: number
  timeoutMs: number
}

const CLOSED_PATTERNS = [
  "target closed",
  "context was destroyed",
  "execution context was destroyed",
  "page is closed",
  "browser has been closed",
  "connection closed",
  "crash",
]

function isContextLostError(error: unknown): boolean {
  const message = (error instanceof Error ? error.message : String(error)).toLowerCase()
  return CLOSED_PATTERNS.some((pattern) => message.includes(pattern))
}

class Semaphore {
  private active = 0
  private readonly queue: Array<() => void> = []

  constructor(private readonly capacity: number) {}

  async acquire(signal?: AbortSignal): Promise<() => void> {
    if (signal?.aborted) throw abortedError()
    if (this.active < this.capacity) {
      this.active++
      return this.release.bind(this, { released: false })
    }
    return new Promise<() => void>((resolve, reject) => {
      const onAbort = () => {
        const index = this.queue.indexOf(grant)
        if (index !== -1) this.queue.splice(index, 1)
        signal?.removeEventListener("abort", onAbort)
        reject(abortedError())
      }
      const grant = () => {
        signal?.removeEventListener("abort", onAbort)
        this.active++
        resolve(this.release.bind(this, { released: false }))
      }
      this.queue.push(grant)
      signal?.addEventListener("abort", onAbort, { once: true })
    })
  }

  private release(token: { released: boolean }): void {
    if (token.released) return
    token.released = true
    this.active--
    const next = this.queue.shift()
    if (next) next()
  }
}

export class QwenWebTransport {
  private readonly browser: QwenWebBrowser
  private readonly metadataTimeoutMs: number
  private readonly idleTimeoutMs: number
  private readonly reasoningIdleTimeoutMs: number
  private readonly slots: Semaphore
  private readonly flushBytes: number
  private readonly flushMs: number
  private readonly states = new Map<string, StreamState>()
  private readonly boundPages = new WeakSet<QwenWebPage>()
  private readonly bindingInFlight = new WeakMap<QwenWebPage, Promise<void>>()
  private readonly wafCapturePages = new WeakSet<QwenWebPage>()
  private readonly capturedWafSignals: Record<string, string> = {}
  private capturedWafAt = 0
  private wafHarvestMissedAt = 0
  private readonly wafHardWaitMs: number
  private readonly wafHarvestCooldownMs: number
  private readonly encoder = new TextEncoder()
  private requestCounter = 0

  constructor(options?: QwenWebTransportOptions) {
    this.browser = options?.browser ?? sharedBrowser()
    this.metadataTimeoutMs =
      options?.metadataTimeoutMs ?? readNumber(QWEN_WEB_ENV.metadataTimeoutMs, QWEN_WEB_DEFAULTS.metadataTimeoutMs)
    this.idleTimeoutMs =
      options?.idleTimeoutMs ?? readNumber(QWEN_WEB_ENV.idleTimeoutMs, QWEN_WEB_DEFAULTS.idleTimeoutMs)
    this.reasoningIdleTimeoutMs =
      options?.reasoningIdleTimeoutMs ??
      readNumber(QWEN_WEB_ENV.reasoningIdleTimeoutMs, QWEN_WEB_DEFAULTS.reasoningIdleTimeoutMs)
    this.slots = new Semaphore(options?.maxStreams ?? readNumber(QWEN_WEB_ENV.maxStreams, QWEN_WEB_DEFAULTS.maxStreams))
    this.flushBytes = options?.flushBytes ?? 512
    this.flushMs = options?.flushMs ?? 8
    this.wafHardWaitMs = options?.wafHardWaitMs ?? WAF_SIGNAL_HARD_WAIT_MS
    this.wafHarvestCooldownMs = options?.wafHarvestCooldownMs ?? WAF_HARVEST_COOLDOWN_MS
    this.browser.onPageOpen((page) => this.attachWafCapture(page))
  }

  idleBudgetMs(reasoning: boolean): number {
    return reasoning ? this.reasoningIdleTimeoutMs : this.idleTimeoutMs
  }

  /** One-shot JSON/text request executed inside the page. */
  async requestJson(method: string, path: string, options?: RequestOptions): Promise<JsonResponse> {
    const signal = options?.signal
    if (signal?.aborted) throw abortedError()
    const url = qwenWebUrl(path)
    const headers = { ...pageRequestHeaders(), ...options?.headers }
    const timeoutMs = options?.timeoutMs ?? this.metadataTimeoutMs
    const body = options?.body
    const referrer = options?.referrer
    try {
      const page = await this.browser.ensureOnOrigin(signal, { steer: options?.allowNavigate ?? true })
      return await page.evaluate(
        async (arg: {
          url: string
          method: string
          headers: Record<string, string>
          body?: string
          referrer?: string
          timeoutMs: number
        }) => {
          const controller = new AbortController()
          const timer = setTimeout(() => controller.abort(), arg.timeoutMs)
          try {
            const response = await fetch(arg.url, {
              method: arg.method,
              credentials: "include",
              headers: arg.headers,
              body: arg.body,
              signal: controller.signal,
              ...(arg.referrer ? { referrer: arg.referrer } : {}),
            })
            const text = await response.text().catch(() => "")
            return {
              status: response.status,
              statusText: response.statusText,
              contentType: response.headers.get("content-type") ?? "",
              body: text,
            }
          } finally {
            clearTimeout(timer)
          }
        },
        { url, method, headers, body, referrer, timeoutMs },
      )
    } catch (error) {
      throw this.translatePageError(error, signal)
    }
  }

  /** Streaming request relayed incrementally through the binding bridge. */
  async requestStream(
    method: string,
    path: string,
    options?: RequestOptions & { reasoning?: boolean },
  ): Promise<StreamResponse> {
    const signal = options?.signal
    if (signal?.aborted) throw abortedError()
    const releaseSlot = await this.slots.acquire(signal)
    try {
      const page = await this.browser.ensureOnOrigin(signal, { steer: options?.allowNavigate ?? true })
      await this.ensureBinding(page)
      return await this.startStream(page, method, path, options, releaseSlot)
    } catch (error) {
      releaseSlot()
      throw this.translatePageError(error, signal)
    }
  }

  /**
   * One-shot request executed from Node against the real origin.
   *
   * The page-context bridge fetch is indistinguishable today, but Alibaba's
   * WAF holds page-originated traffic to the chat endpoints unless it is
   * driven by the site's own instrumentation, while a plain HTTP request with
   * the browser's cookies plus the client's WAF signal headers (see
   * `collectWafSignals`) completes normally. Chat creation and completions
   * therefore run over this raw path; lighter endpoints keep the bridge.
   */
  async rawRequestJson(method: string, path: string, options?: RequestOptions): Promise<JsonResponse> {
    return this.rawRequest(method, path, options, false) as Promise<JsonResponse>
  }

  /** Streaming `.stream` is buffered/pumped from Node against the real origin. */
  async rawRequestStream(
    method: string,
    path: string,
    options?: RequestOptions & { reasoning?: boolean },
  ): Promise<StreamResponse> {
    return this.rawRequest(method, path, options, true) as Promise<StreamResponse>
  }

  private async rawRequest(
    method: string,
    path: string,
    options: (RequestOptions & { reasoning?: boolean }) | undefined,
    stream: boolean,
  ): Promise<JsonResponse | StreamResponse> {
    const rawStart = Date.now()
    const traceTransport = (label: string, extra?: Record<string, unknown>) =>
      debug("transport", `turn timing: ${label}`, { ms: Date.now() - rawStart, ...extra })
    const signal = options?.signal
    if (signal?.aborted) throw abortedError()
    const releaseSlot = await this.slots.acquire(signal)
    try {
      const page = await this.browser.ensureOnOrigin(signal, { steer: options?.allowNavigate ?? true })
      const readyAt = Date.now()
      const [cookies, signals] = await Promise.all([this.browserCookies(page), this.collectWafSignals(page, stream)])
      debug("transport", "raw request prepared", {
        ensureMs: readyAt - rawStart,
        signalsMs: Date.now() - readyAt,
        waf: [...WAF_CAPTURE_KEYS].filter((key) => signals[key]),
        clientHints: [...CLIENT_HINT_KEYS].filter((key) => Boolean(signals[key])),
      })
      const headers = rawRequestHeaders(pageRequestHeaders(), cookies, signals, options)
      const url = qwenWebUrl(path)
      const timeoutMs = options?.timeoutMs ?? this.metadataTimeoutMs
      const controller = new AbortController()
      const onAbort = () => controller.abort()
      signal?.addEventListener("abort", onAbort, { once: true })
      const deadline = setTimeout(() => {
        controller.abort(new Error(`Qwen request timed out waiting for a response after ${timeoutMs}ms.`))
      }, timeoutMs)
      try {
        const response = await fetch(url, {
          method,
          headers,
          body: options?.body,
          signal: controller.signal,
        })
        const contentType = response.headers.get("content-type") ?? ""
        if (!stream) {
          return {
            status: response.status,
            statusText: response.statusText,
            contentType,
            body: await response.text().catch(() => ""),
          }
        }
        traceTransport("response headers received", { status: response.status })
        return {
          status: response.status,
          contentType,
          stream: pumpRawStream(response.body, controller, this.idleBudgetMs(options?.reasoning ?? false), signal, () =>
            traceTransport("first stream chunk"),
          ),
          abort: () => controller.abort(),
        }
      } finally {
        clearTimeout(deadline)
        signal?.removeEventListener("abort", onAbort)
      }
    } catch (error) {
      throw this.translateRawError(error, signal)
    } finally {
      releaseSlot()
    }
  }

  private async browserCookies(page: QwenWebPage): Promise<string> {
    const origin = qwenWebOrigin()
    const cookies = await page.context().cookies([origin])
    return cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join("; ")
  }

  private hasFullWafPair(signals: WafSignals): boolean {
    return Boolean(signals["bx-ua"] && signals["bx-umidtoken"])
  }

  private attachWafCapture(page: QwenWebPage): void {
    if (this.wafCapturePages.has(page)) return
    this.wafCapturePages.add(page)
    page.on("request", (request) => {
      let headers: Record<string, string>
      let url = ""
      let method = ""
      try {
        headers = request.headers()
        url = request.url()
        method = request.method()
      } catch {
        return
      }
      if (!url.includes("/api/")) return
      const present: string[] = []
      for (const key of WAF_SIGNAL_KEYS) {
        const value = headers[key]
        if (typeof value === "string" && value) {
          this.capturedWafSignals[key] = value
          present.push(key)
        }
      }
      if (present.length > 0) {
        if (WAF_CAPTURE_KEYS.some((key) => present.includes(key))) {
          this.capturedWafAt = Date.now()
          this.wafHarvestMissedAt = 0
        }
        let path = ""
        try {
          path = new URL(url).pathname.slice(0, 60)
        } catch {
          path = url.slice(0, 60)
        }
        debug("transport", "page api request carries WAF headers", {
          method,
          path,
          present,
        })
      }
    })
  }

  private async collectWafSignals(page: QwenWebPage, hardWait = false): Promise<WafSignals> {
    // Evaluated code runs inside the browser and is carried there as
    // serialized source, so it must only reference its own arguments and
    // page globals — never module-level constants (they get renamed by the
    // bundler, then ReferenceError inside the page).
    await page.evaluate(
      (arg: { storageKey: string; keys: string[] }) => {
        const { storageKey, keys } = arg
        const store = (globalThis as unknown as Record<string, unknown>)[storageKey] as
          | (Record<string, string | boolean> & { installed?: boolean })
          | undefined
        if (store?.installed) return
        const signals: Record<string, string | boolean> = { installed: true }
        const origFetch = window.fetch.bind(window)
        ;(window as unknown as Record<string, unknown>).fetch = ((input: RequestInfo | URL, init?: RequestInit) => {
          const url = typeof input === "string" ? input : input instanceof URL ? input.href : (input as Request).url
          if (url.includes("/api/") && init?.headers) {
            const headers = init.headers instanceof Headers ? init.headers : new Headers(init.headers)
            for (const key of keys) {
              const value = headers.get(key)
              if (value) signals[key] = value
            }
          }
          return origFetch(input, init)
        })
        ;(globalThis as unknown as Record<string, unknown>)[storageKey] = signals
      },
      { storageKey: WAF_SPY_STORAGE_KEY, keys: [...WAF_SIGNAL_KEYS] },
    )
    for (const candidate of page.context().pages()) this.attachWafCapture(candidate)
    const context = await collectClientContext(page)
    const readStore = async (): Promise<WafSignals> => {
      let spy: WafSignals = {}
      try {
        spy = await page.evaluate(
          (arg: { storageKey: string; keys: string[] }): WafSignals => {
            const store = (globalThis as unknown as Record<string, unknown>)[arg.storageKey] as Record<string, unknown> | undefined
            const out: Record<string, string> = {}
            if (store)
              for (const key of arg.keys) {
                const value = store[key]
                if (typeof value === "string") out[key] = value
              }
            return out
          },
          { storageKey: WAF_SPY_STORAGE_KEY, keys: [...WAF_SIGNAL_KEYS] },
        )
      } catch {
        // Navigation between pages destroys the execution context mid-poll; the
        // CDP request capture below is unaffected, so degrade to it alone.
      }
      return { ...spy, ...this.capturedWafSignals }
    }
    if (this.hasFullWafPair(this.capturedWafSignals) && Date.now() - this.capturedWafAt < WAF_PAIR_TTL_MS) {
      debug("transport", "waf pairs already captured; skipping harvest", {
        present: [...WAF_SIGNAL_KEYS].filter((key) => Boolean(this.capturedWafSignals[key])),
      })
      return { ...context, ...this.capturedWafSignals }
    }
    if (!this.hasFullWafPair(this.capturedWafSignals) && Date.now() - this.wafHarvestMissedAt < this.wafHarvestCooldownMs && hardWait) {
      debug("transport", "waf pair unreachable last harvest; skipping poll", {
        present: [...WAF_SIGNAL_KEYS].filter((key) => Boolean(this.capturedWafSignals[key])),
      })
      return { ...context, ...this.capturedWafSignals }
    }
    const current = await pollWafSignals(readStore, Date.now() + (hardWait ? this.wafHardWaitMs : 0), hardWait)
    if (hardWait && !this.hasFullWafPair(current)) this.wafHarvestMissedAt = Date.now()
    return { ...context, ...current }
  }

  private translateRawError(error: unknown, signal?: AbortSignal): unknown {
    if (QwenWebError.isInstance(error)) return error
    if (signal?.aborted) return abortedError()
    const message = error instanceof Error ? error.message : String(error)
    if (/timed out|stalled/i.test(message)) {
      return new QwenWebError({ code: "timeout", retryable: true, message: message.slice(0, 300) })
    }
    if (isAbortLike(error)) {
      return new QwenWebError({
        code: "timeout",
        retryable: true,
        message: `Qwen request aborted while awaiting a response: ${message.slice(0, 200)}`,
      })
    }
    return classifyTransportFailure(error)
  }

  private async startStream(
    page: QwenWebPage,
    method: string,
    path: string,
    options: (RequestOptions & { reasoning?: boolean }) | undefined,
    releaseSlot: () => void,
  ): Promise<StreamResponse> {
    const signal = options?.signal
    const requestId = `qw-${Date.now().toString(36)}-${++this.requestCounter}-${Math.random().toString(36).slice(2)}`
    const state: StreamState = { chunks: [], done: false, error: undefined, metadata: undefined, waiters: new Set() }
    this.states.set(requestId, state)

    let released = false
    const release = () => {
      if (released) return
      released = true
      this.states.delete(requestId)
      for (const waiter of state.waiters) waiter()
      state.waiters.clear()
      releaseSlot()
    }

    const abort = () => {
      // Fire-and-forget: the page may already be gone; rejection is swallowed.
      void page
        .evaluate(
          (arg: { abortersKey: string; requestId: string }) => {
            const registry = (globalThis as unknown as Record<string, unknown>)[arg.abortersKey] as
              | Map<string, AbortController>
              | undefined
            registry?.get(arg.requestId)?.abort()
            return true
          },
          { abortersKey: QWEN_WEB_STREAM_ABORTERS_KEY, requestId },
        )
        .catch(() => false)
      state.error = state.error ?? abortedError()
      state.done = true
      release()
    }

    const onAbort = () => abort()
    signal?.addEventListener("abort", onAbort, { once: true })

    const url = qwenWebUrl(path)
    const headers = { ...pageRequestHeaders(), ...options?.headers }
    const scriptArgs: BridgeScriptArgs = {
      url,
      method,
      headers,
      body: options?.body,
      referrer: options?.referrer,
      requestId,
      bindingName: QWEN_WEB_STREAM_BINDING,
      abortersKey: QWEN_WEB_STREAM_ABORTERS_KEY,
      flushBytes: this.flushBytes,
      flushMs: this.flushMs,
      timeoutMs: this.metadataTimeoutMs,
    }

    try {
      await page.evaluate(runBridgeFetch, scriptArgs)
    } catch (error) {
      signal?.removeEventListener("abort", onAbort)
      release()
      throw error
    }

    const metadata = await this.waitForMetadata(state, signal).catch((error) => {
      signal?.removeEventListener("abort", onAbort)
      abort()
      throw error
    })
    signal?.removeEventListener("abort", onAbort)
    if (signal) signal.addEventListener("abort", onAbort, { once: true })

    const idleMs = this.idleBudgetMs(options?.reasoning ?? false)
    const stream = this.assembleStream(requestId, state, idleMs, signal, () => {
      signal?.removeEventListener("abort", onAbort)
      abort()
      release()
    })
    return {
      status: metadata.status,
      contentType: metadata.contentType,
      stream,
      abort: () => {
        signal?.removeEventListener("abort", onAbort)
        abort()
      },
    }
  }

  private assembleStream(
    requestId: string,
    state: StreamState,
    idleMs: number,
    signal: AbortSignal | undefined,
    cleanup: () => void,
  ): ReadableStream<Uint8Array> {
    let finished = false
    const finish = (controller: ReadableStreamDefaultController<Uint8Array>, error?: Error) => {
      if (finished) return
      finished = true
      cleanup()
      if (error) controller.error(error)
      else controller.close()
    }
    const pump = async (controller: ReadableStreamDefaultController<Uint8Array>): Promise<void> => {
      for (;;) {
        if (signal?.aborted) {
          finish(controller, abortedError())
          return
        }
        if (state.chunks.length > 0) {
          controller.enqueue(state.chunks.shift()!)
          return
        }
        if (state.done) {
          finish(controller, state.error)
          return
        }
        const arrived = await this.waitForChunk(state, idleMs).catch((error) => error as Error)
        if (arrived instanceof Error) {
          finish(controller, arrived)
          return
        }
      }
    }
    return new ReadableStream<Uint8Array>({
      pull: (controller) => pump(controller),
      cancel: () => {
        finishSlots(this.states.get(requestId))
        cleanup()
      },
    })
  }

  private waitForChunk(state: StreamState, idleMs: number): Promise<void> {
    if (state.chunks.length > 0 || state.done) return Promise.resolve()
    return new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => {
        state.waiters.delete(wake)
        reject(
          new QwenWebError({
            code: "timeout",
            retryable: true,
            message: `Qwen stream stalled: no data for ${idleMs}ms.`,
          }),
        )
      }, idleMs)
      timer.unref?.()
      const wake = () => {
        clearTimeout(timer)
        state.waiters.delete(wake)
        resolve()
      }
      state.waiters.add(wake)
      if (state.chunks.length > 0 || state.done) wake()
    })
  }

  private waitForMetadata(
    state: StreamState,
    signal: AbortSignal | undefined,
  ): Promise<{ status: number; contentType: string }> {
    if (state.metadata) return Promise.resolve(state.metadata)
    if (state.error) return Promise.reject(state.error)
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        cleanup()
        reject(
          new QwenWebError({
            code: "timeout",
            retryable: true,
            message: `Qwen stream timed out waiting for response headers after ${this.metadataTimeoutMs}ms.`,
          }),
        )
      }, this.metadataTimeoutMs)
      timer.unref?.()
      const onAbort = () => {
        cleanup()
        reject(abortedError())
      }
      const wake = () => {
        if (state.metadata) {
          cleanup()
          resolve(state.metadata)
          return
        }
        if (state.error || state.done) {
          cleanup()
          reject(
            state.error ??
              new QwenWebError({
                code: "upstream_error",
                retryable: true,
                message: "Qwen stream ended before response headers arrived.",
              }),
          )
        }
      }
      const cleanup = () => {
        clearTimeout(timer)
        state.waiters.delete(wake)
        signal?.removeEventListener("abort", onAbort)
      }
      state.waiters.add(wake)
      signal?.addEventListener("abort", onAbort, { once: true })
      wake()
    })
  }

  private async ensureBinding(page: QwenWebPage): Promise<void> {
    if (this.boundPages.has(page)) return
    const inFlight = this.bindingInFlight.get(page)
    if (inFlight) return inFlight
    const install = page
      .exposeBinding(QWEN_WEB_STREAM_BINDING, (_source: unknown, requestId: string, event: BridgeEvent) => {
        this.onBridgeEvent(requestId, event)
      })
      .then(() => {
        this.boundPages.add(page)
        this.bindingInFlight.delete(page)
      })
      .catch((error) => {
        this.bindingInFlight.delete(page)
        // Re-installing on an already-bound page (e.g. after recreation with
        // the same object) is harmless.
        if (error instanceof Error && /already exists|registered/i.test(error.message)) {
          this.boundPages.add(page)
          return
        }
        throw error
      })
    this.bindingInFlight.set(page, install)
    return install
  }

  private onBridgeEvent(requestId: string, event: BridgeEvent): void {
    const state = this.states.get(requestId)
    if (!state) return
    switch (event.type) {
      case "headers":
        state.metadata = { status: event.status, contentType: event.contentType }
        break
      case "chunk":
        if (event.data) state.chunks.push(this.encoder.encode(event.data))
        break
      case "done":
        state.done = true
        break
      case "error": {
        const error =
          event.errorName === "AbortError"
            ? abortedError()
            : new QwenWebError({
                code: "network_error",
                retryable: true,
                message: `Qwen stream failed in the browser: ${event.message.slice(0, 300)}`,
              })
        state.error = error
        state.done = true
        break
      }
    }
    for (const waiter of state.waiters) waiter()
    state.waiters.clear()
  }

  private translatePageError(error: unknown, signal?: AbortSignal): QwenWebError {
    if (QwenWebError.isInstance(error)) {
      if (error.code === "aborted") return error
      if (isContextLostError(error)) this.browser.invalidatePage()
      return error
    }
    if (isAbortLike(error) || signal?.aborted) return abortedError()
    if (isContextLostError(error)) {
      this.browser.invalidatePage()
      debug("transport", "page/context lost; invalidated for recreation")
      return new QwenWebError({
        code: "browser_error",
        retryable: true,
        cause: error,
        message: "The Qwen browser page was closed or crashed. Retrying will recreate it.",
      })
    }
    return classifyTransportFailure(error)
  }
}

/**
 * Runs inside the page: performs the fetch with the browser session and
 * relays the response incrementally through the exposed binding. Returns
 * immediately so the Node side is never blocked on a whole generation.
 */
async function runBridgeFetch(arg: BridgeScriptArgs): Promise<boolean> {
  const registry = globalThis as unknown as Record<string, unknown>
  const notify = registry[arg.bindingName] as ((requestId: string, event: BridgeEvent) => Promise<void>) | undefined
  if (typeof notify !== "function") throw new Error("Qwen stream binding is unavailable")

  let aborters = registry[arg.abortersKey] as Map<string, AbortController> | undefined
  if (!aborters) {
    aborters = new Map<string, AbortController>()
    registry[arg.abortersKey] = aborters
  }
  const controller = new AbortController()
  aborters.set(arg.requestId, controller)
  const timeout = setTimeout(() => controller.abort(), arg.timeoutMs)

  void (async () => {
    try {
      const response = await fetch(arg.url, {
        method: arg.method,
        credentials: "include",
        headers: arg.headers,
        body: arg.body,
        signal: controller.signal,
        ...(arg.referrer ? { referrer: arg.referrer } : {}),
      })
      clearTimeout(timeout)
      await notify(arg.requestId, {
        type: "headers",
        status: response.status,
        contentType: response.headers.get("content-type") ?? "",
      })
      if (!response.body) {
        await notify(arg.requestId, { type: "done" })
        return
      }
      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffered = ""
      let lastFlush = Date.now()
      let firstSent = false
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        if (!value) continue
        buffered += decoder.decode(value, { stream: true })
        if (!firstSent || buffered.length >= arg.flushBytes || Date.now() - lastFlush >= arg.flushMs) {
          const data = buffered
          buffered = ""
          firstSent = true
          lastFlush = Date.now()
          await notify(arg.requestId, { type: "chunk", data })
        }
      }
      buffered += decoder.decode()
      if (buffered) await notify(arg.requestId, { type: "chunk", data: buffered })
      await notify(arg.requestId, { type: "done" })
    } catch (error) {
      clearTimeout(timeout)
      try {
        await notify(arg.requestId, {
          type: "error",
          message: error instanceof Error ? error.message : String(error),
          errorName: error instanceof Error ? error.name : undefined,
        })
      } catch {
        // Node already went away; nothing to report to.
      }
    } finally {
      aborters?.delete(arg.requestId)
    }
  })()

  return true
}

function finishSlots(state: StreamState | undefined): void {
  if (!state) return
  state.done = true
  for (const waiter of state.waiters) waiter()
  state.waiters.clear()
}

function readNumber(name: string, fallback: number): number {
  const raw = process.env[name]
  if (!raw) return fallback
  const parsed = Number.parseInt(raw, 10)
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback
}

/**
 * Browser context headers the completion broker keys on (`user-agent`,
 * `sec-ch-ua*`, `accept-language`). They are read straight from the browser's
 * own navigator state, so they are always available without waiting for the
 * site to emit a request; the fetch spy additionally layers the site's WAF
 * signals on top.
 */
function collectClientContext(page: QwenWebPage): Promise<WafSignals> {
  return page
    .evaluate(
      (_arg: string): WafSignals => {
        const ua = navigator.userAgent
        const data = (navigator as unknown as { userAgentData?: { brands?: Array<{ brand: string; version: string }>; platform?: string } }).userAgentData
      let secChUa: string | undefined
      if (Array.isArray(data?.brands) && data.brands.length > 0) {
        secChUa = data.brands.map((b) => `${JSON.stringify(b.brand)};v="${b.version}"`).join(", ")
      } else {
        const match = /(?:Headless)?Chrome\/(\d+)/.exec(ua)
        secChUa = match
          ? `"Not=A?Brand";v="99", "Chromium";v="${match[1]}", "Chrome";v="${match[1]}"`
          : undefined
      }
      const languages = navigator.languages?.length ? navigator.languages : [navigator.language]
      const acceptLanguage =
        languages.length > 1
          ? languages.map((lang, index) => (index === 0 ? lang : `${lang};q=0.9`)).join(", ")
          : languages[0]?.startsWith("en-")
            ? `${languages[0]},en;q=0.9`
            : (languages[0] ?? "en-US,en;q=0.9")
      return {
        "user-agent": ua,
        "accept-language": acceptLanguage,
        "sec-ch-ua": secChUa,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": typeof data?.platform === "string" ? JSON.stringify(data.platform) : undefined,
      }
      },
      QWEN_WEB_CLIENT_CONTEXT_ARG,
    )
    .catch(() => ({}))
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

async function pollWafSignals(
  readStore: () => Promise<WafSignals>,
  deadline: number,
  requireFullPair = false,
): Promise<WafSignals> {
  const ok = (current: WafSignals): boolean =>
    requireFullPair
      ? Boolean(current["bx-ua"] && current["bx-umidtoken"])
      : Boolean(current["bx-v"] || current["bx-umidtoken"])
  for (;;) {
    const current = await readStore()
    if (ok(current)) return current
    if (Date.now() >= deadline) return current
    await sleep(200)
  }
}

/**
 * Headers for raw-node requests to the Qwen origin.
 *
 * These mirror the web client exactly: plain request headers plus the WAF
 * signal headers captured from the live page (`bx-*`, `version`) and the
 * browser's real cookies. Cookies are deliberately NOT replayed from a cache:
 * they are read from the live browser context right before each request, so
 * rotation/expiry is always observed by the server.
 */
function rawRequestHeaders(
  base: Record<string, string>,
  cookies: string,
  signals: WafSignals,
  options?: { referrer?: string },
): Record<string, string> {
  const headers: Record<string, string> = {
    ...base,
    accept: "application/json",
    "x-accel-buffering": "no",
    origin: qwenWebOrigin(),
    // WAF/UMID client versions are static (the web client always sends them);
    // live-captured values overlay them when the spy has already seen traffic.
    "bx-v": signals["bx-v"] ?? QWEN_WEB_BX_V,
    version: signals["version"] ?? QWEN_WEB_CLIENT_VERSION,
  }
  for (const key of WAF_CAPTURE_KEYS) {
    const value = signals[key]
    if (value) headers[key] = value
  }
  for (const key of CLIENT_HINT_KEYS) {
    const value = signals[key]
    if (value) headers[key] = value
  }
  if (cookies) headers.cookie = cookies
  if (options?.referrer) headers.referer = qwenWebUrl(options.referrer)
  return headers
}

/**
 * Relay an upstream byte stream with an idle watchdog. The watchdog shares
 * the fetch's AbortController so a stall tears down the connection; caller
 * aborts end the stream cleanly (closes, no error part).
 */
function pumpRawStream(
  upstream: ReadableStream<Uint8Array> | null,
  controller: AbortController,
  idleMs: number,
  signal?: AbortSignal,
  onFirstChunk?: () => void,
): ReadableStream<Uint8Array> {
  if (!upstream) {
    return new ReadableStream<Uint8Array>({
      start: (inner) => inner.close(),
    })
  }
  const reader = upstream.getReader()
  let timedOut = false
  let closed = false
  let firstChunkReported = false
  let timer: ReturnType<typeof setTimeout> | undefined
  const kick = () => {
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => {
      timedOut = true
      controller.abort(new Error(`Qwen stream stalled (no data for ${idleMs}ms).`))
    }, idleMs)
  }
  const stop = () => {
    if (timer) clearTimeout(timer)
    if (closed) return
    closed = true
    if (controller.signal.aborted) return
    try {
      reader.releaseLock()
    } catch {
      // A read is in flight (cancel raced the relay); reader.cancel() frees it.
    }
  }
  return new ReadableStream<Uint8Array>({
    start: kick,
    pull: async (inner) => {
      let chunk: Uint8Array
      try {
        const result = await reader.read()
        if (result.done) {
          stop()
          inner.close()
          return
        }
        chunk = result.value
        if (!firstChunkReported) {
          firstChunkReported = true
          onFirstChunk?.()
        }
      } catch (error) {
        stop()
        if (timedOut) {
          throw new QwenWebError({
            code: "timeout",
            retryable: true,
            message: `Qwen stream stalled (no data for ${idleMs}ms).`,
          })
        }
        if (controller.signal.aborted || (signal as AbortSignal | undefined)?.aborted) {
          inner.close()
          return
        }
        throw classifyTransportFailure(error)
      }
      kick()
      inner.enqueue(chunk)
    },
    cancel: () => {
      stop()
      return reader.cancel().catch(() => {})
    },
  })
}

/** Process-wide shared transport. Tests construct `QwenWebTransport` directly. */
let shared: QwenWebTransport | undefined

export function sharedTransport(): QwenWebTransport {
  if (!shared) shared = new QwenWebTransport()
  return shared
}

/** Test seam: replace or clear the shared instance. */
export function setSharedTransport(transport: QwenWebTransport | undefined): void {
  shared = transport
}
