export * as NarrationDetector from "./narration"

/**
 * Guidance appended to tool output when a narration-only shell command is detected.
 * Produced by the harness; never generated by the model.
 */
export const GUIDANCE =
  "\n\n[AlphaCode]\nThis command only described an intended action. It did not perform that action.\nCall the appropriate tool directly instead of using bash to narrate the action."

/**
 * Narration-verb prefixes that indicate the model is describing an intended
 * action rather than performing one. Compared case-insensitively.
 */
const NARRATION_PREFIXES = [
  "calling ",
  "using ",
  "trying ",
  "searching ",
  "i will ",
  "i am ",
  "i'm ",
  "executing ",
  "invoking ",
  "fetching ",
]

/**
 * Returns true when `command` is a single narration-only shell statement.
 *
 * Detection strategy — all conditions must hold:
 *
 *  1. The raw command string contains no shell operator characters
 *     (; | & < >). This check is not quote-aware: an operator inside
 *     quoted text (e.g. echo "foo > bar") will also cause rejection.
 *     That is intentional — false negatives are much safer than false
 *     positives for this detector.
 *
 *  2. The leading word is `echo` or `Write-Output` (case-insensitive).
 *     `printf` is accepted only in the trivial single-argument form
 *     (`printf "text"`) to avoid false-positives from format strings
 *     with additional arguments (`printf "Calling %s\n" foo`).
 *
 *  3. The remainder of the command contains no detected shell expansions
 *     ($VAR, ${VAR}, $(...)) or sub-shell metacharacters (` or ().
 *     This check is also not quote-aware by design.
 *
 *  4. The remainder, after stripping one layer of outer quotes, begins
 *     with one of the NARRATION_PREFIXES (compared case-insensitively).
 *
 * The detector is intentionally not a shell parser. It will produce false
 * negatives (miss some narration commands) rather than risk false positives
 * on legitimate output.
 */
export function isNarrationOnly(command: string): boolean {
  const trimmed = command.trim()

  // Gate 1 — single statement only.
  // Reject any command that contains a shell operator outside of quotes.
  // We use a simple character scan rather than a full parser; the
  // characters ; | & < > are sufficient to catch all compound forms.
  if (/[;|&<>]/.test(trimmed)) return false

  // Gate 2 — extract the leading command word and the remainder.
  // Match: optional-quotes-free command word, then the rest of the line.
  const cmdMatch = trimmed.match(/^(\S+)\s+(.+)$/)
  if (!cmdMatch) return false
  const [, cmdRaw, rest] = cmdMatch as [string, string, string]
  const cmd = cmdRaw.toLowerCase()

  // Gate 2a — printf: only allow the trivial single-argument form.
  // If there are multiple whitespace-separated tokens after printf, bail out
  // regardless of narration prefix, to avoid format-string false positives.
  if (cmd === "printf") {
    // The rest must be exactly one token (possibly quoted, no unquoted spaces).
    // Strip a single outer quote pair, then check that no further unquoted
    // whitespace exists — i.e. there is only one argument.
    const singleArg = stripOuterQuotes(rest.trim())
    // If the original rest (trimmed) starts and ends with a matching quote and
    // contains no unquoted whitespace in between, it is a single argument.
    const isSingleToken =
      (rest.trim() === `"${singleArg}"` || rest.trim() === `'${singleArg}'`) ||
      // Or: no whitespace at all (unquoted single word)
      !/\s/.test(rest.trim())
    if (!isSingleToken) return false
  } else if (cmd !== "echo" && cmd !== "write-output") {
    return false
  }

  // Gate 3 — reject anything that looks like a shell expansion or metachar.
  // Checked against the raw remainder before quote-stripping so that expansions
  // inside double quotes ("$VAR", "${VAR}", "$(...)") are also caught.
  // Not quote-aware by design: a literal "(" in quoted text will also reject.
  if (/\$[\w{(]/.test(rest)) return false
  if (/[`(]/.test(rest)) return false

  // Gate 4 — strip one layer of outer quotes and check for a narration prefix.
  const literal = stripOuterQuotes(rest.trim()).trimStart().toLowerCase()
  return literal === "searching" || NARRATION_PREFIXES.some((prefix) => literal.startsWith(prefix))
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Strips a single layer of matching ' or " quotes from a string, if present. */
function stripOuterQuotes(value: string): string {
  if (value.length >= 2) {
    const first = value[0]
    const last = value[value.length - 1]
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return value.slice(1, -1)
    }
  }
  return value
}
